# Generated by Django 5.2.17 on 2026-08-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cryptoprice_price_alter_cryptoprice_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoprice',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='cryptoprice',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptoprice',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cryptoprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='cryptoprice',
            index=models.Index(fields=['symbol', '-timestamp'], name='core_crypto_symbol_c631af_idx'),
        ),
    ]
