# Generated by Django 5.2.17 on 2026-08-08 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cryptoprice_options_cryptoprice_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoprice',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
