# Generated by Django 5.2.17 on 2026-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coin_pricehistory_delete_cryptoprice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Coin', 'verbose_name_plural': 'Coins'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Price History', 'verbose_name_plural': 'Price Histories'},
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='price_change_percentage_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
