# Generated by Django 5.2.17 on 2026-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_coin_options_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
    ]
