# Generated by Django 5.2.17 on 2026-08-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_coin_max_supply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='volume_24h',
            new_name='total_volume',
        ),
    ]
