# Generated by Django 5.2.17 on 2026-08-16 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_volume_24h_pricehistory_total_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coin_id',
            new_name='gecko_id',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='core.coin'),
        ),
    ]
