# Generated by Django 5.2.17 on 2026-08-16 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_coin_id_coin_gecko_id_alter_pricehistory_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
