# Generated by Django 5.2.17 on 2026-08-24 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pricehistory_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinCurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('price_change_percentage_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.coin')),
            ],
        ),
    ]
