# Generated by Django 5.2.17 on 2026-09-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_coincurrentdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coincurrentdata',
            options={'verbose_name': 'Coin Current Data', 'verbose_name_plural': 'Coins Current Data'},
        ),
        migrations.AddField(
            model_name='coin',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coincurrentdata',
            name='ath',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='coincurrentdata',
            name='atl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='coincurrentdata',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='ath',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='atl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='gecko_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coincurrentdata',
            name='coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_data', to='core.coin'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_data', to='core.coin'),
        ),
    ]
