# Generated by Django 5.2.17 on 2026-08-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_coincurrentdata_options_coin_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coincurrentdata',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='gecko_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
