# Generated by Django 5.2.17 on 2026-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coincurrentdata_circulating_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
