# Generated by Django 5.2.17 on 2026-08-31 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pricehistory_circulating_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_data', to='core.coin'),
        ),
    ]
