# Generated by Django 5.2.17 on 2026-08-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coincurrentdata_ath_coincurrentdata_atl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='ath',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='atl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
